# Site settings
title: Automatic Breadcrumb for jekyll
email: info@comsysto.com
description: > # this means to ignore newlines until "baseurl:"
  An automatic breadcrumb for jekyll hosted on GitHub Pages
baseurl: "/jekyll-breadcrumb-for-github-pages" # the subpath of your site, e.g. /blog/
url: "https://comsysto.github.io" # the base hostname & protocol for your site
github_username: comsysto

# Build settings
markdown: kramdown
